

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [released]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      cache-name: cache1
      YARN_CACHE_FOLDER: yarn-cache-dir
      NODE_VERSION: 14
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: "yarn-cache-dir"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install
      - run: yarn prepack
  automerge:
    name: Auto-merge
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: 'Merge (if dependabot)'
      uses: fastify/github-action-merge-dependabot@v1
      with:
        github-token: ${{secrets.github_token}}
    - name: "Checkout source code"
      uses: "actions/checkout@v2"
    - name: "Setup Node.js"
      uses: "actions/setup-node@v1"
      with:
        node-version: 12
    - name: 'Version bump'
      uses: 'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag-prefix: 'v'
  publish:
    name: Yarn publish
    if: github.event_name == 'release'
    needs: test
    environment: publish
    runs-on: ubuntu-latest
    env:
      cache-name: cache1
      YARN_CACHE_FOLDER: yarn-cache-dir
      NODE_VERSION: 14
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: "yarn-cache-dir"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
      - run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
