
name: testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      cache-name: cache1
      YARN_CACHE_FOLDER: yarn-cache-dir
      NODE_VERSION: 14
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true # garamond
      - name: Restore Cache
        uses: actions/cache@v2
        with: 
          path: "yarn-cache-dir"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install
      - run: yarn prepack
