name: Pubilish new version
on:
  release:
    types: [released]
jobs:
  build:
    environment: publish
    runs-on: ubuntu-latest
    env:
      cache-name: cache1
      YARN_CACHE_FOLDER: yarn-cache-dir
      NODE_VERSION: 14
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: "yarn-cache-dir"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
      - run: yarn prepack
      - run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
